name: Connect 4 Compassion
favicon: null
layout_spectrum: 0.9408706047106534
typography_spectrum: 0.3984625262673944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1895928292069584
  lightness: 0.49747875006869435
  saturation: 0.2681089183315635
  rhythmicContrast: 0.07380249630659819
purpose: []
